import math
import os
import struct
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
ASSETS = os.path.normpath(os.path.join(HERE, "..", "assets"))
os.makedirs(ASSETS, exist_ok=True)

def write_obj(name, mtllib, usemtl, verts, uvs, norms, faces):
    path = os.path.join(ASSETS, name + ".obj")
    with open(path, "w") as f:
        f.write(f"# generated by tools/gen_assets.py\n")
        f.write(f"mtllib {mtllib}\n")
        for v in verts:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        for t in uvs:
            f.write(f"vt {t[0]:.6f} {t[1]:.6f}\n")
        for n in norms:
            f.write(f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}\n")
        f.write(f"usemtl {usemtl}\n")
        f.write("s 1\n")
        for a, b, c in faces:

            f.write(f"f {a+1}/{a+1}/{a+1} {b+1}/{b+1}/{b+1} {c+1}/{c+1}/{c+1}\n")
    print("wrote", path, f"({len(faces)} tris)")

def write_mtl(name, materials):
    path = os.path.join(ASSETS, name)
    with open(path, "w") as f:
        f.write("# generated by tools/gen_assets.py\n")
        for m in materials:
            f.write(f"newmtl {m['name']}\n")
            f.write("Ka {0:.4f} {1:.4f} {2:.4f}\n".format(*m["Ka"]))
            f.write("Kd {0:.4f} {1:.4f} {2:.4f}\n".format(*m["Kd"]))
            f.write("Ks {0:.4f} {1:.4f} {2:.4f}\n".format(*m["Ks"]))
            f.write("Ns {0:.2f}\n".format(m["Ns"]))
            f.write("d 1.0\nillum 2\n")
            if m.get("map_Kd"):
                f.write(f"map_Kd {m['map_Kd']}\n")
            f.write("\n")
    print("wrote", path)

def gen_sphere(stacks=48, slices=96, radius=1.0):
    verts, uvs, norms, faces = [], [], [], []
    for i in range(stacks + 1):
        v = i / stacks
        phi = v * math.pi
        for j in range(slices + 1):
            u = j / slices
            theta = u * 2.0 * math.pi
            nx = math.sin(phi) * math.cos(theta)
            ny = math.cos(phi)
            nz = math.sin(phi) * math.sin(theta)
            verts.append((nx * radius, ny * radius, nz * radius))
            norms.append((nx, ny, nz))
            uvs.append((u, 1.0 - v))
    row = slices + 1
    for i in range(stacks):
        for j in range(slices):
            a = i * row + j
            b = a + row
            faces.append((a, b, a + 1))
            faces.append((a + 1, b, b + 1))
    return verts, uvs, norms, faces

def gen_torus(rings=64, sides=32, R=1.0, r=0.35):
    verts, uvs, norms, faces = [], [], [], []
    for i in range(rings + 1):
        u = i / rings
        a = u * 2 * math.pi
        ca, sa = math.cos(a), math.sin(a)
        for j in range(sides + 1):
            v = j / sides
            b = v * 2 * math.pi
            cb, sb = math.cos(b), math.sin(b)
            x = (R + r * cb) * ca
            y = r * sb
            z = (R + r * cb) * sa
            nx, ny, nz = cb * ca, sb, cb * sa
            verts.append((x, y, z))
            norms.append((nx, ny, nz))
            uvs.append((u * 4.0, v * 1.0))
    row = sides + 1
    for i in range(rings):
        for j in range(sides):
            a = i * row + j
            c = a + row
            faces.append((a, c, a + 1))
            faces.append((a + 1, c, c + 1))
    return verts, uvs, norms, faces

def gen_cube(s=1.0):

    verts, uvs, norms, faces = [], [], [], []
    faces_def = [
        ((0, 0, 1), [(-s, -s, s), (s, -s, s), (s, s, s), (-s, s, s)]),
        ((0, 0, -1), [(s, -s, -s), (-s, -s, -s), (-s, s, -s), (s, s, -s)]),
        ((-1, 0, 0), [(-s, -s, -s), (-s, -s, s), (-s, s, s), (-s, s, -s)]),
        ((1, 0, 0), [(s, -s, s), (s, -s, -s), (s, s, -s), (s, s, s)]),
        ((0, 1, 0), [(-s, s, s), (s, s, s), (s, s, -s), (-s, s, -s)]),
        ((0, -1, 0), [(-s, -s, -s), (s, -s, -s), (s, -s, s), (-s, -s, s)]),
    ]
    uv_quad = [(0, 0), (1, 0), (1, 1), (0, 1)]
    for n, quad in faces_def:
        base = len(verts)
        for k, p in enumerate(quad):
            verts.append(p)
            norms.append(n)
            uvs.append(uv_quad[k])
        faces.append((base, base + 1, base + 2))
        faces.append((base, base + 2, base + 3))
    return verts, uvs, norms, faces

def gen_plane(size=1.0, tile=8.0):
    verts = [(-size, 0, -size), (size, 0, -size), (size, 0, size), (-size, 0, size)]
    norms = [(0, 1, 0)] * 4
    uvs = [(0, 0), (tile, 0), (tile, tile), (0, tile)]
    faces = [(0, 1, 2), (0, 2, 3)]
    return verts, uvs, norms, faces

def write_png(path, w, h, rgba):
    def chunk(tag, data):
        c = tag + data
        return struct.pack(">I", len(data)) + c + struct.pack(">I", zlib.crc32(c) & 0xFFFFFFFF)

    raw = bytearray()
    stride = w * 4
    for y in range(h):
        raw.append(0)
        raw.extend(rgba[y * stride:(y + 1) * stride])
    sig = b"\x89PNG\r\n\x1a\n"
    ihdr = struct.pack(">IIBBBBB", w, h, 8, 6, 0, 0, 0)
    out = sig + chunk(b"IHDR", ihdr)
    out += chunk(b"IDAT", zlib.compress(bytes(raw), 9))
    out += chunk(b"IEND", b"")
    with open(path, "wb") as f:
        f.write(out)
    print("wrote", path, f"({w}x{h})")

def tex_checker(w=512, h=512, c1=(210, 180, 140), c2=(90, 70, 50), n=8):
    buf = bytearray(w * h * 4)
    for y in range(h):
        for x in range(w):
            cell = ((x * n // w) + (y * n // h)) & 1
            r, g, b = c1 if cell else c2
            i = (y * w + x) * 4
            buf[i:i + 4] = bytes((r, g, b, 255))
    return buf

def tex_bricks(w=512, h=512):
    buf = bytearray(w * h * 4)
    mortar = (60, 60, 65)
    brick = (150, 70, 55)
    bh, bw = 64, 128
    for y in range(h):
        row = y // bh
        offset = (bw // 2) if (row & 1) else 0
        for x in range(w):
            xx = (x + offset) % bw
            yy = y % bh
            is_mortar = xx < 6 or yy < 6
            r, g, b = mortar if is_mortar else brick

            shade = 1.0 - 0.15 * (yy / bh)
            i = (y * w + x) * 4
            buf[i:i + 4] = bytes((int(r * shade), int(g * shade), int(b * shade), 255))
    return buf

def main():

    write_png(os.path.join(ASSETS, "checker.png"), 512, 512, tex_checker())
    write_png(os.path.join(ASSETS, "bricks.png"), 512, 512, tex_bricks())

    write_mtl("scene.mtl", [
        {"name": "shiny_red", "Ka": (0.05, 0.01, 0.01), "Kd": (0.85, 0.18, 0.15),
         "Ks": (1.0, 1.0, 1.0), "Ns": 128.0},
        {"name": "blue_plastic", "Ka": (0.01, 0.02, 0.05), "Kd": (0.20, 0.45, 0.85),
         "Ks": (0.6, 0.6, 0.6), "Ns": 48.0},
        {"name": "gold_metal", "Ka": (0.08, 0.06, 0.01), "Kd": (0.78, 0.62, 0.20),
         "Ks": (1.0, 0.9, 0.6), "Ns": 200.0},
        {"name": "checker_floor", "Ka": (0.05, 0.05, 0.05), "Kd": (0.8, 0.8, 0.8),
         "Ks": (0.25, 0.25, 0.25), "Ns": 16.0, "map_Kd": "checker.png"},
        {"name": "brick_cube", "Ka": (0.05, 0.03, 0.03), "Kd": (0.9, 0.9, 0.9),
         "Ks": (0.3, 0.3, 0.3), "Ns": 24.0, "map_Kd": "bricks.png"},
    ])

    write_obj("sphere", "scene.mtl", "shiny_red", *gen_sphere())
    write_obj("torus", "scene.mtl", "gold_metal", *gen_torus())
    write_obj("cube", "scene.mtl", "brick_cube", *gen_cube(0.6))
    write_obj("plane", "scene.mtl", "checker_floor", *gen_plane(12.0, 12.0))
    write_obj("sphere_blue", "scene.mtl", "blue_plastic", *gen_sphere())

if __name__ == "__main__":
    main()
